apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    devEnvApprovers:
    - codebymaulana
    environmentGitOwner: codebymaulana
    gitKind: github
    gitName: github
    zone: asia-southeast1-a
    project: airy-dialect-457307-h8
    gitServer: https://github.com
    provider: gke
    registry: gcr.io
    terraform: true
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: vault
  vault: {}
  webhook: lighthouse
