apiVersion: v1
kind: ConfigMap
metadata:
  name: helmfile-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: helmfile
    spec:
      allowConcurrency: true
      discover:
        fileName: helmfile.yaml
      generate:
        command:
          - bash
          - -c
          - |
            helmfile -e default --selector argocd=true -n "$ARGOCD_APP_NAMESPACE" template --include-crds -q
      lockRepo: false
