helmDefaults:
  kubeContext: "gke_airy-dialect-457307-h8_asia-southeast1-a_gke-cluster"
  timeout: 900

templates:
  default: &default
    chart: stable/{{`{{ .Release.Name }}`}}
    namespace: default
    missingFileHandler: Warn
    values:
    - values/testing-project/{{`{{ .Release.Name }}`}}/values.yaml
    secrets:
    - values/testing-project/{{`{{ .Release.Name }}`}}/secrets.yaml

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.18.0

  - name: nginx
    namespace: nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.12.3

  - name: simple-app
    <<: *default
    chart: ../charts/simple-app

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 9.2.4

  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: 27.20.0

  - name: vault
    namespace: vault
    chart: hashicorp/vault
    version: 0.30.0

repositories:
  - name: stable
    url: "https://charts.helm.sh/stable"
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: hashicorp
    url: https://helm.releases.hashicorp.com