# .github/workflows/build‑push‑gcr.yml
name: Build - Push image to GCR - Bump Helm tag

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-bump:
    runs-on: ubuntu-latest
    environment: vars
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Login to GAR
      uses: docker/login-action@v3
      with:
        registry: asia-southeast1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: app
        push: true
        tags: ${{ vars.PATH_GCR }}:${{ github.sha }}

    - name: Update Helm image tag manually
      run: |
        echo "Updating image tag to ${{ github.sha }}"
        yq eval '.image.tag = "${{ github.sha }}"' -i releases/helmfile.d/values/testing-project/simple-app/values.yaml

    - name: Commit and push updated image tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add releases/helmfile.d/values/testing-project/simple-app/values.yaml
        git commit -m "bump image tag simple-app to ${{ github.sha }}"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.token_github }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: '${{ vars.PATH_GCR }}:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'