# .github/workflows/build‑push‑gcr.yml
name: Build - Push image to GCR - Bump Helm tag

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id:  ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - run: gcloud --quiet auth configure-docker

    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: app
        push: true
        tags: ${{ vars.PATH_GCR }}:${{ github.sha }}

    # - name: Bump Helm tag
    #   uses: fjogeleit/yaml-update-action@v0.16.1
    #   with:
    #     valueFile: charts/my-app/values.yaml
    #     propertyPath: image.tag
    #     value: ${{ env.IMAGE_TAG }}
    #     commitChange: true
    #     message: "ci(chart): bump image tag to ${{ env.IMAGE_TAG }}"

