# .github/workflows/build‑push‑gcr.yml
name: Build - Push image to GCR - Bump Helm tag

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-bump:
    runs-on: ubuntu-latest
    environment: vars
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Login to GAR
      uses: docker/login-action@v3
      with:
        registry: asia-southeast1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: app
        push: true
        tags: ${{ vars.PATH_GCR }}:${{ github.sha }}

    - name: Bump Helm tag
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: releases/helmfile.d/values/testing-project/simple-app/values.yaml
        propertyPath: image.tag
        value: ${{ github.sha }}
        commitChange: true
        message: "bump image tag to ${{ github.sha }}"
        repository: codebymaulana/e2e-terraform-project
        token: ${{ secrets.github_token }

